ScreenManager:
    SplashScreen:
    LoginScreen:
    MainScreen:

<SplashScreen>:
    name: "splash"
    BoxLayout:
        orientation: "vertical"
        padding: 30
        spacing: 20
        Label:
            text: "[color=#FFD700][b]الجنرال سيد المصري[/b]\nVIP[/color]"
            markup: True
            font_size: 38

<LoginScreen>:
    name: "login"
    GridLayout:
        cols: 1
        padding: 25
        spacing: 15

        TextInput:
            id: email
            hint_text: "Email"
            multiline: False

        TextInput:
            id: password
            hint_text: "Password"
            password: True
            multiline: False

        TextInput:
            id: phone
            hint_text: "Phone"
            multiline: False

        Label:
            id: status
            text: ""
            markup: True

        Button:
            text: "⭐ تسجيل الدخول VIP"
            on_release: root.login_user()

<MainScreen>:
    name: "main"
    GridLayout:
        cols: 1
        padding: 20
        spacing: 20

        Label:
            id: user_info
            text: ""
            markup: True
            font_size: 20

        Button:
            text: "📩 تواصل تليجرام"
            on_release: app.open_telegram()

        Button:
            text: "🚪 تسجيل خروج"
            on_release: app.logout()
